### ISSUE TITLE
Wildcards not supported

### ISSUE THREAD

**Issue by anony253** [williamcruzme/vue-gates#17]
I assume this is not compatible with permission wildcards, as I can't get it to work

using: `{{ this.$laravel.getPermissions() }}` results in `[ "*.view", "*.create" ]` but `v-can="'users.create'"` doesn't trigger

Ref: [Spatie wildcard permissions docs](https://docs.spatie.be/laravel-permission/v3/basic-usage/wildcard-permissions/)

Could you please add support for wildcards ?

**Comment by williamcruzme** [comment]
Great idea, I'll work on it!

**Comment by williamcruzme** [comment]
Resolved in v2.0.0! 🎉
