### ISSUE TITLE
Alias not supporting arguments

### ISSUE THREAD

**Issue by anony253** [williamcruzme/vue-gates#18]
> `<!-- Alias -->`
> `<button v-can="'add articles'">Add Article</button>`
> `Check for any permission in a list:`
> `<button v-permission:any="'add articles|edit articles'">Configure</button>`

you can't actually use `v-can:any` but would be really nice

**Comment by williamcruzme** [comment]
Great idea, I'll work on it!

**Comment by williamcruzme** [comment]
Resolved in v2.0.0! 🎉
