### ISSUE TITLE
Vue 3 support?

### ISSUE THREAD

**Issue by gaetandezeiraud** [williamcruzme/vue-gates#23]
Currently, I have the following error `Uncaught TypeError: Cannot set property '$gates' of undefined`.
At : 

```
var index = {
    install: function install(Vue) {
      var options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
      var gate = new Gate(options);
      Vue.prototype.$gates = gate; // here
      Vue.gates = gate;
      registerDirectives(Vue);
    }
  };
```

**Comment by gaetandezeiraud** [comment]
A fix https://github.com/williamcruzme/vue-gates/pull/24

**Comment by williamcruzme** [comment]
Excellent 🥇, I'll work on that

**Comment by williamcruzme** [comment]
I'm having trouble getting the directive name, it turns out that `binding.name` doesn't exist 😢
