### ISSUE TITLE
Vue-gates Directives Doest work with Bootstrap-vue tabs

### ISSUE THREAD

**Issue by momurad18** [williamcruzme/vue-gates#26]
Hello sir,

I tried your plugin is work perfect but when I want to hide tabs using v-role="'admin'" it only hides the tab content but it doesnt hide the tab-nav from navigation bar

<b-tab name="tab1" v-role="'admin'">
</b-tab>

Thank you

**Comment by williamcruzme** [comment]
Hey @utechs 

In this https://github.com/bootstrap-vue/bootstrap-vue/issues/5477#issuecomment-640889429 issue, they try to do the same :)

```vue
<b-tab title="Users" :title-item-class="isAdmin"></b-tab>
```

```javascript
computed: {
  isAdmin() {
    return this.$gates.hasRole('admin') ? '' : 'd-none';
  }
}
```
