### ISSUE TITLE
v-permission not working well

### ISSUE THREAD

**Issue by pintukalasva** [williamcruzme/vue-gates#28]
I have dashboard permission.
console.log(this.$gates.hasPermission('dashboard1')) it's show true.

**Comment by williamcruzme** [comment]
You're right! Fixing...

**Comment by biholaindrasinh** [comment]
No, I make custom role permission.

**Comment by williamcruzme** [comment]
Hey @pintukalasva @biholaindrasinh, fixed!

https://github.com/williamcruzme/vue-gates/releases/tag/v2.1.2

**Comment by DarthSmirnov** [comment]
@williamcruzme Hi. Bug still reproduced
