### ISSUE TITLE
superRole not working

### ISSUE THREAD

**Issue by wimil** [williamcruzme/vue-gates#29]
I have added the superRole setting, something strange happens with the v-permission directive it works, but with the $ gates.hasPermission() method it does not recognize the superRole.

**Comment by darkons** [comment]
Same issue. superRole works fine with vue directives but not with directives as functions.

**Comment by luckasdc** [comment]
Same here..

**Comment by williamcruzme** [comment]
You're right! Fixing...

**Comment by disjointed** [comment]
Any news on this issue?

**Comment by williamcruzme** [comment]
Hey @disjointed @luckasdc @wimil @darkons, fixed!

https://github.com/williamcruzme/vue-gates/releases/tag/v2.1.2
