### ISSUE TITLE
It is not possible to differentiate between the permissions that contain "-"

### ISSUE THREAD

**Issue by eslamoo** [williamcruzme/vue-gates#32]
If we have two permissions that partially contains same string but they totally different permissions the package cant  differentiate between them, For example: we have : 
`v-permission="'admin.dashboard.overview.ranking-data.no-of-visits'"`
and 
`v-permission="'admin.dashboard.overview.ranking-data.no-of-visits-per-customer'"`

These two permissions sounds the same to the Vue-Gates.

**Comment by williamcruzme** [comment]
Hey @eslamoo, fixed!

https://github.com/williamcruzme/vue-gates/releases/tag/v2.1.2
