### ISSUE TITLE
Bug to check similar permissions

### ISSUE THREAD

**Issue by luilliarcec** [williamcruzme/vue-gates#36]
When I have a permission `"security.create.role"` and I check with the directive` v-can` or `v-permission` with the name `"security.create.roles"` or `"security.create.roless"`, it is validated by true, when it should be false, since such permission does not exist.

**Comment by williamcruzme** [comment]
Hey @luilliarcec, fixed!

https://github.com/williamcruzme/vue-gates/releases/tag/v2.1.2
